### Get all students
GET {{host}}/{{version}}/student
Authorization: Bearer {{token}}


### Get a student
GET {{host}}/{{version}}/student/login?email=a00000001@tec.mx&password=Abc123456 HTTP/1.1


### Create a student
POST {{host}}/{{version}}/student/register
Content-Type: application/json

{
    "student_id": "a00000005",
    "first_name": "John",
    "last_name": "Wayne",
    "email": "a00000005@tec.mx",
    "password": "Abc123456"
}


### Get classes a student is registered to
GET {{host}}/{{version}}/student/a00000001/class
Authorization: Bearer {{token}}
