### Get all teachers
GET {{host}}/{{version}}/teacher
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiQTAwMDAwMDAxIiwiaWF0IjoxNjgyMjIzMzMxLCJleHAiOjE2ODI4MjgxMzF9.2ZIWxx3il8lcLtAb9Q1ntoZ0d0XttR8TnkMNoW6-_Z0

### Get a teacher
GET {{host}}/{{version}}/teacher/login?email=l00000001@tec.com&password=Abc123456 HTTP/1.1

### Create a teacher
POST {{hostname}}:{{port}}/{{version}}/teacher/register
Content-Type: application/json

{
    "teacher_id": "l00000001",
    "first_name": "Dan",
    "last_name": "Perez",
    "email": "dan.perez@tec.mx",
    "password": "test_pass"
}
