### Submit an assignment
PUT {{host}}/{{version}}/homework/submit
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "student_id": "a01734902",
  "homework_id": 1,
  "questions": [
    {
      "question_h_id": 30,
      "type": "open",
      "difficulty_id": 1,
      "source_code": "#I am here\nname=input();last=input();print(\"Hola\",name,last+\", ¡bienvenido!\")",
      "question": {
        "tests": [
          {
            "input": ["Juan", "Pérez"],
            "output": "Hola Juan Pérez, ¡bienvenido!"
          },
          {
            "input": ["Ana", "Gómez"],
            "output": "Hola Ana Gómez, ¡bienvenido!"
          },
          {
            "input": ["Pedro", "Ramírez"],
            "output": "Hola Pedro Ramírez, ¡bienvenido!"
          },
          {
            "input": ["María", "Hernández"],
            "output": "Hola María Hernández, ¡bienvenido!"
          }
        ]
      }
    },
    {
      "question_h_id": 31,
      "type": "open",
      "source_code": "name=input();last=input();print(\"Hola\",name,last+\", ¡bienvenido!\")",
      "question": {
        "tests": [
          {
            "input": ["Juan", "Pérez"],
            "output": "Hola Juan Pérez, ¡bienvenido!"
          },
          {
            "input": ["Ana", "Gómez"],
            "output": "Hola Ana Gómez, ¡bienvenido!"
          },
          {
            "input": ["Pedro", "Ramírez"],
            "output": "Hola Pedro Ramírez, ¡bienvenido!"
          },
          {
            "input": ["María", "Hernández"],
            "output": "Hola María Hernández, ¡bienvenido!"
          }
        ]
      }
    },
    {
      "question_h_id": 79,
      "type": "closed",
      "difficulty_id": 1,
      "selected_choice": 0,
      "question": {
        "answer": 1,
        "options": [
          {
            "text": "4",
            "explanation": "Correcto"
          }
        ]
      }
    }
  ]
}


