### Run code
PUT {{host}}/{{version}}/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "source_code": "print('Hello world')",
  "tests": [
    {
      "input": ["Juan", "Perez"],
      "output": "Hola Juan Perez ¡bienvenido!"
    }
  ]
}

### Run code
PUT {{host}}/{{version}}/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "source_code": "name=input();print(\"Hola, \" + name + \"!\")",
  "tests": [
    {
      "input": "Andre",
      "output": "Hola, Andr!"
    },
    {
      "input": "0001",
      "output": "Hola, 0001!"
    },
    {
      "input": "_XAMP45",
      "output": "Hola, _XAMP45!"
    },
    {
      "input": "andre",
      "output": "Hola, andre"
    }
  ]
}


### Submit a challenge
PUT {{host}}/{{version}}/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "source_code": "x=int(input());y=int(input());print([x+y,x*y])",
  "tests": [
    {
      "input": [2, 3],
      "output": [5, 6]
    },
    {
      "input": [10, -5],
      "output": [5, -50]
    },
    {
      "input": [0, 8],
      "output": [8, 0]
    }
  ]
}


### Submit an assignment
PUT {{host}}/{{version}}/challenge/submit
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "student_id": "a01734902",
  "challenge_id": 1,
  "questions": [
    {
      "question_id": 30,
      "type": "open",
      "difficulty_id": 1,
      "source_code": "#I am here\nname=input();last=input();print(\"Hola\",name,last+\", ¡bienvenido!\")",
      "question": {
        "tests": [
          {
            "input": ["Juan", "Pérez"],
            "output": "Hola Juan Pérez, ¡bienvenido!"
          },
          {
            "input": ["Ana", "Gómez"],
            "output": "Hola Ana Gómez, ¡bienvenido!"
          },
          {
            "input": ["Pedro", "Ramírez"],
            "output": "Hola Pedro Ramírez, ¡bienvenido!"
          },
          {
            "input": ["María", "Hernández"],
            "output": "Hola María Hernández, ¡bienvenido!"
          }
        ]
      }
    },
    {
      "question_id": 31,
      "type": "open",
      "source_code": "name=input();last=input();print(\"Hola\",name,last+\", ¡bienvenido!\")",
      "question": {
        "tests": [
          {
            "input": ["Juan", "Pérez"],
            "output": "Hola Juan Pérez, ¡bienvenido!"
          },
          {
            "input": ["Ana", "Gómez"],
            "output": "Hola Ana Gómez, ¡bienvenido!"
          },
          {
            "input": ["Pedro", "Ramírez"],
            "output": "Hola Pedro Ramírez, ¡bienvenido!"
          },
          {
            "input": ["María", "Hernández"],
            "output": "Hola María Hernández, ¡bienvenido!"
          }
        ]
      }
    },
    {
      "question_id": 79,
      "type": "closed",
      "difficulty_id": 1,
      "selected_choice": 0,
      "question": {
        "answer": 1,
        "options": [
          {
            "text": "4",
            "explanation": "Correcto"
          }
        ]
      }
    }
  ]
}

