### Run code
PUT {{host}}/{{version}}/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "source_code": "name=input();print(\"Hola, \" + name + \"!\")",
  "shown_tests": [
    {
      "input": "Andre",
      "output": "Hola, Andre!"
    },
    {
      "input": "0001",
      "output": "Hola, 0001!"
    },
    {
      "input": "_XAMP45",
      "output": "Hola, _XAMP45!"
    },
    {
      "input": "andre",
      "output": "Hola, andre"
    }
  ]
}


### Run code
PUT {{host}}/{{version}}/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "source_code": "x=int(input());y=int(input());print([x+y,x*y])",
  "shown_tests": [
    {
      "input": [2, 3],
      "output": [5, 6]
    },
    {
      "input": [10, -5],
      "output": [5, -50]
    },
    {
      "input": [0, 8],
      "output": [8, 0]
    }
  ]
}


### Submit an assignment
PUT {{host}}/{{version}}/submit
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "student_id": "A0000001",
  "questions": [
    {
      "question_id": 1,
      "type": "open",
      "source_code": "the code that goes here",
      "shown_tests": [
        {
          "input": "1 2",
          "output": "3"
        },
        {
          "input": "10 20",
          "output": "30"
        },
        {
          "input": "1 2",
          "output": "3"
        }
      ]
    },
    {
      "question_id": 2,
      "type": "open",
      "source_code": "x=int(input());y=int(input());print([x+y,x*y])",
      "shown_tests": [
        {
          "input": "1 2",
          "output": "3"
        },
        {
          "input": "10 20",
          "output": "30"
        },
        {
          "input": "1 2",
          "output": "3"
        }
      ]
    },
    {
      "question_id": 3,
      "type": "close",
      "user_answer": 1,
      "answer": 1
    }
  ]
}

