### Get all classes
GET {{host}}/{{version}}/class
Authorization: Bearer {{token}}

### Get attributes of a class
GET {{host}}/{{version}}/class/thisIsCl3
Authorization: Bearer {{token}}

### Create a class
POST {{host}}/{{version}}/class/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class_id": "thisIsCl4",
    "is_finished": false,
    "finished_date": "2022-03-17",
    "days": ["LU", "MA"],
    "start_time": "08:00:00",
    "end_time": "10:00:00",
    "subject_id": "CS10101",
    "teacher_id": "L00000001"
}


### Register a student to a class
POST {{host}}/{{version}}/class/thisIsCl/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "student_id": "a00000005"
}


### Get students of a class
GET {{host}}/{{version}}/class/thisIsCl/students
Authorization: Bearer {{token}}
